# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginpage(object):
    def setupUi(self, loginpage):
        loginpage.setObjectName("loginpage")
        loginpage.resize(1440, 812)
        loginpage.setMinimumSize(QtCore.QSize(1440, 812))
        loginpage.setMaximumSize(QtCore.QSize(1440, 812))
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        loginpage.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(loginpage)
        self.centralwidget.setObjectName("centralwidget")
        self.denglu = PushButton(self.centralwidget)
        self.denglu.setGeometry(QtCore.QRect(570, 440, 301, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.denglu.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.denglu.setFont(font)
        self.denglu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.denglu.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :20px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.denglu.setObjectName("denglu")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1440, 812))
        self.label.setMinimumSize(QtCore.QSize(1440, 812))
        self.label.setMaximumSize(QtCore.QSize(1440, 812))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/登录.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.quxiao = QtWidgets.QPushButton(self.centralwidget)
        self.quxiao.setGeometry(QtCore.QRect(570, 520, 301, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 127, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.quxiao.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.quxiao.setFont(font)
        self.quxiao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quxiao.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :20px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.quxiao.setObjectName("quxiao")
        self.password = PasswordLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(660, 300, 201, 33))
        self.password.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改为白色文本 */\n"
"    background-color: transparent; /* 修改为透明背景 */\n"
"    border: none; /* 去除边框 */\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 0.3); /* 底部边框设为白色（半透明） */\n"
"    border-radius: 5px;\n"
"    border: none; /* 移除所有边框 */\n"
"    outline: none; /* 移除浏览器默认轮廓 */\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"/* 对于需要显示密码的场景，可设置input[type=\"password\"]样式 */\n"
"input[type=\"password\"] {\n"
"    color: white; /* 密码文本为白色 */\n"
"}\n"
"\n"
"/* 其他悬停、聚焦和禁用状态的样式保持不变... *\n"
"")
        self.password.setObjectName("password")
        self.username = LineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(660, 250, 201, 33))
        self.username.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.username.setObjectName("username")
        self.lineEdit_3 = LineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(660, 350, 101, 33))
        self.lineEdit_3.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.CheckBox = CheckBox(self.centralwidget)
        self.CheckBox.setGeometry(QtCore.QRect(570, 390, 93, 41))
        self.CheckBox.setStyleSheet("CheckBox {\n"
"    color: #00c2e6;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 1px;\n"
"    background-color: #03063f;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.48);\n"
"    background-color: rgba(255, 255, 255, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(255, 255, 255, 0.56);\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(255, 255, 255, 0.27);\n"
"    background-color: rgba(255, 255, 255, 0.12);\n"
"}\n"
"\n"
"/* 修改选中状态的背景颜色 */\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #00c2e6; /* 更改为#00c2e6 */\n"
"}\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(255, 255, 255, 0.44);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(255, 255, 255, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(128, 128, 128);\n"
"    background-color: rgb(128, 128, 128);\n"
"}")
        self.CheckBox.setObjectName("CheckBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 90, 90))
        self.label_2.setMinimumSize(QtCore.QSize(90, 90))
        self.label_2.setMaximumSize(QtCore.QSize(90, 90))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/img/院徽.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.denglu.raise_()
        self.quxiao.raise_()
        self.password.raise_()
        self.username.raise_()
        self.lineEdit_3.raise_()
        self.CheckBox.raise_()
        self.label_2.raise_()
        loginpage.setCentralWidget(self.centralwidget)

        self.retranslateUi(loginpage)
        self.quxiao.clicked.connect(loginpage.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(loginpage)
        loginpage.setTabOrder(self.denglu, self.quxiao)

    def retranslateUi(self, loginpage):
        _translate = QtCore.QCoreApplication.translate
        loginpage.setWindowTitle(_translate("loginpage", "陆军军事交通学院武器库管理系统"))
        self.denglu.setText(_translate("loginpage", "登     录"))
        self.denglu.setShortcut(_translate("loginpage", "Return"))
        self.quxiao.setText(_translate("loginpage", "取     消"))
        self.quxiao.setShortcut(_translate("loginpage", "Esc"))
        self.CheckBox.setText(_translate("loginpage", "记住密码"))
from qfluentwidgets import CheckBox, LineEdit, PasswordLineEdit, PushButton

