# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wuqixinxi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wuqixinxi(object):
    def setupUi(self, wuqixinxi):
        wuqixinxi.setObjectName("wuqixinxi")
        wuqixinxi.resize(1440, 812)
        wuqixinxi.setMinimumSize(QtCore.QSize(1440, 812))
        wuqixinxi.setMaximumSize(QtCore.QSize(1440, 812))
        self.centralwidget = QtWidgets.QWidget(wuqixinxi)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroung = QtWidgets.QLabel(self.centralwidget)
        self.backgroung.setGeometry(QtCore.QRect(0, 0, 1440, 812))
        self.backgroung.setMinimumSize(QtCore.QSize(1440, 812))
        self.backgroung.setMaximumSize(QtCore.QSize(1440, 812))
        self.backgroung.setText("")
        self.backgroung.setPixmap(QtGui.QPixmap(":/img/主界面背景.png"))
        self.backgroung.setScaledContents(True)
        self.backgroung.setObjectName("backgroung")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 90, 90))
        self.label.setMinimumSize(QtCore.QSize(90, 90))
        self.label.setMaximumSize(QtCore.QSize(90, 90))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/院徽.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 160, 164, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.zhgl = PushButton(self.layoutWidget)
        self.zhgl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zhgl.setAutoFillBackground(False)
        self.zhgl.setStyleSheet("PushButton {\n"
"    color:rgb(255, 255, 255);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    \n"
"    background-image: url(:/img/背景.png);\n"
"    \n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
" \n"
"    font: 13pt \"黑体\";\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background-image: url(:/背景.png);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled  {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:hover,\n"
" {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransprentPushButton:disabled,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.zhgl.setObjectName("zhgl")
        self.verticalLayout.addWidget(self.zhgl)
        self.wqtj = PushButton(self.layoutWidget)
        self.wqtj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wqtj.setStyleSheet("PushButton {\n"
"    color:rgb(255, 255, 255);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    \n"
"    background-image: url(:/img/背景.png);\n"
"    \n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
" \n"
"    font: 13pt \"黑体\";\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background-image: url(:/背景.png);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled  {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:hover,\n"
" {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransprentPushButton:disabled,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.wqtj.setObjectName("wqtj")
        self.verticalLayout.addWidget(self.wqtj)
        self.crkgl = PushButton(self.layoutWidget)
        self.crkgl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.crkgl.setStyleSheet("PushButton {\n"
"    color:rgb(255, 255, 255);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    \n"
"    background-image: url(:/img/背景.png);\n"
"    \n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
" \n"
"    font: 13pt \"黑体\";\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background-image: url(:/背景.png);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled  {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:hover,\n"
" {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransprentPushButton:disabled,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.crkgl.setObjectName("crkgl")
        self.verticalLayout.addWidget(self.crkgl)
        self.qzxx = PushButton(self.layoutWidget)
        self.qzxx.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qzxx.setStyleSheet("PushButton {\n"
"    color:rgb(255, 255, 255);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    \n"
"    background-image: url(:/img/背景.png);\n"
"    \n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
" \n"
"    font: 13pt \"黑体\";\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background-image: url(:/背景.png);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled  {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:hover,\n"
" {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransprentPushButton:disabled,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.qzxx.setObjectName("qzxx")
        self.verticalLayout.addWidget(self.qzxx)
        self.whby = PushButton(self.layoutWidget)
        self.whby.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.whby.setStyleSheet("PushButton {\n"
"    color:rgb(255, 255, 255);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    \n"
"    background-image: url(:/img/背景.png);\n"
"    \n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
" \n"
"    font: 13pt \"黑体\";\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background-image: url(:/背景.png);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled  {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:hover,\n"
" {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransprentPushButton:disabled,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.whby.setObjectName("whby")
        self.verticalLayout.addWidget(self.whby)
        self.qywqxx = PushButton(self.layoutWidget)
        self.qywqxx.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qywqxx.setStyleSheet("PushButton {\n"
"    color:rgb(255, 255, 255);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    \n"
"    background-image: url(:/img/背景.png);\n"
"    \n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
" \n"
"    font: 13pt \"黑体\";\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background-image: url(:/背景.png);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled  {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:hover,\n"
" {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransprentPushButton:disabled,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.qywqxx.setObjectName("qywqxx")
        self.verticalLayout.addWidget(self.qywqxx)
        self.afgl = PushButton(self.layoutWidget)
        self.afgl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.afgl.setStyleSheet("PushButton {\n"
"    color:rgb(255, 255, 255);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    \n"
"    background-image: url(:/img/背景.png);\n"
"    \n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
" \n"
"    font: 13pt \"黑体\";\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background-image: url(:/背景.png);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled  {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:hover,\n"
" {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransprentPushButton:disabled,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.afgl.setObjectName("afgl")
        self.verticalLayout.addWidget(self.afgl)
        self.PushButton_8 = PushButton(self.layoutWidget)
        self.PushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_8.setStyleSheet("PushButton {\n"
"    color:rgb(255, 255, 255);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    \n"
"    background-image: url(:/img/背景.png);\n"
"    \n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
" \n"
"    font: 13pt \"黑体\";\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background-image: url(:/背景.png);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled  {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:hover,\n"
" {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransparentPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"TransprentPushButton:disabled,\n"
" {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.PushButton_8.setObjectName("PushButton_8")
        self.verticalLayout.addWidget(self.PushButton_8)
        self.wqtj.raise_()
        self.qzxx.raise_()
        self.whby.raise_()
        self.qywqxx.raise_()
        self.afgl.raise_()
        self.PushButton_8.raise_()
        self.crkgl.raise_()
        self.zhgl.raise_()
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 180, 1221, 561))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.ps_3 = PasswordLineEdit(self.page_0)
        self.ps_3.setGeometry(QtCore.QRect(530, 190, 191, 33))
        self.ps_3.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.ps_3.setObjectName("ps_3")
        self.genggai = PrimaryPushButton(self.page_0)
        self.genggai.setGeometry(QtCore.QRect(430, 420, 301, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.genggai.setFont(font)
        self.genggai.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.genggai.setObjectName("genggai")
        self.ps_1 = PasswordLineEdit(self.page_0)
        self.ps_1.setGeometry(QtCore.QRect(530, 340, 191, 33))
        self.ps_1.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.ps_1.setObjectName("ps_1")
        self.ps_2 = PasswordLineEdit(self.page_0)
        self.ps_2.setGeometry(QtCore.QRect(530, 290, 191, 33))
        self.ps_2.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.ps_2.setObjectName("ps_2")
        self.name_2 = LineEdit(self.page_0)
        self.name_2.setGeometry(QtCore.QRect(530, 240, 191, 33))
        self.name_2.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.name_2.setObjectName("name_2")
        self.name_1 = LineEdit(self.page_0)
        self.name_1.setGeometry(QtCore.QRect(530, 140, 191, 33))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        self.name_1.setFont(font)
        self.name_1.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.name_1.setText("")
        self.name_1.setObjectName("name_1")
        self.label_2 = QtWidgets.QLabel(self.page_0)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1221, 561))
        self.label_2.setStyleSheet("background-image: url(:/img/账号.png);")
        self.label_2.setObjectName("label_2")
        self.zhuce = PushButton(self.page_0)
        self.zhuce.setGeometry(QtCore.QRect(431, 481, 301, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.zhuce.setFont(font)
        self.zhuce.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.zhuce.setObjectName("zhuce")
        self.label_2.raise_()
        self.ps_3.raise_()
        self.genggai.raise_()
        self.ps_1.raise_()
        self.ps_2.raise_()
        self.name_2.raise_()
        self.name_1.raise_()
        self.zhuce.raise_()
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_4 = QtWidgets.QLabel(self.page_1)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 561, 531))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/img/背景.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.TitleLabel = TitleLabel(self.page_1)
        self.TitleLabel.setGeometry(QtCore.QRect(250, 70, 124, 38))
        self.TitleLabel.setStyleSheet("color: rgba(255, 255, 255, 200);")
        self.TitleLabel.setObjectName("TitleLabel")
        self.SubtitleLabel = SubtitleLabel(self.page_1)
        self.SubtitleLabel.setGeometry(QtCore.QRect(180, 170, 221, 27))
        self.SubtitleLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.bq = SubtitleLabel(self.page_1)
        self.bq.setGeometry(QtCore.QRect(170, 340, 141, 27))
        self.bq.setStyleSheet("color: rgb(255, 255, 255);")
        self.bq.setObjectName("bq")
        self.label_5 = QtWidgets.QLabel(self.page_1)
        self.label_5.setGeometry(QtCore.QRect(610, 20, 601, 531))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/img/背景.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.SubtitleLabel_4 = SubtitleLabel(self.page_1)
        self.SubtitleLabel_4.setGeometry(QtCore.QRect(170, 250, 181, 27))
        self.SubtitleLabel_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.ImageLabel = QtWidgets.QLabel(self.page_1)
        self.ImageLabel.setGeometry(QtCore.QRect(670, 70, 500, 400))
        self.ImageLabel.setText("")
        self.ImageLabel.setObjectName("ImageLabel")
        self.wqtj_2 = PushButton(self.page_1)
        self.wqtj_2.setGeometry(QtCore.QRect(830, 470, 162, 30))
        self.wqtj_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wqtj_2.setStyleSheet("PushButton {\n"
"    color:rgb(255, 255, 255);\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    \n"
"    background-image: url(:/img/背景.png);\n"
"    \n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
" \n"
"    font: 13pt \"黑体\";\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"")
        self.wqtj_2.setObjectName("wqtj_2")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(-10, -10, 611, 591))
        self.label_18.setAutoFillBackground(False)
        self.label_18.setStyleSheet("")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/img/背景.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(60, 170, 71, 161))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(167, 173, 214);")
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 40, 311, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.editAddress_2 = LineEdit(self.gridLayoutWidget)
        self.editAddress_2.setObjectName("editAddress_2")
        self.gridLayout.addWidget(self.editAddress_2, 5, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 0, 1, 1)
        self.ZhDatePicker_3 = ZhDatePicker(self.gridLayoutWidget)
        self.ZhDatePicker_3.setObjectName("ZhDatePicker_3")
        self.gridLayout.addWidget(self.ZhDatePicker_3, 3, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 0, 1, 1)
        self.TimePicker_2 = TimePicker(self.gridLayoutWidget)
        self.TimePicker_2.setObjectName("TimePicker_2")
        self.gridLayout.addWidget(self.TimePicker_2, 4, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)
        self.editID_2 = LineEdit(self.gridLayoutWidget)
        self.editID_2.setObjectName("editID_2")
        self.gridLayout.addWidget(self.editID_2, 0, 2, 1, 1)
        self.ZhDatePicker_2 = ZhDatePicker(self.gridLayoutWidget)
        self.ZhDatePicker_2.setObjectName("ZhDatePicker_2")
        self.gridLayout.addWidget(self.ZhDatePicker_2, 1, 2, 1, 1)
        self.TimePicker = TimePicker(self.gridLayoutWidget)
        self.TimePicker.setObjectName("TimePicker")
        self.gridLayout.addWidget(self.TimePicker, 2, 2, 1, 1)
        self.luru = PushButton(self.page_2)
        self.luru.setGeometry(QtCore.QRect(130, 430, 301, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.luru.setFont(font)
        self.luru.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.luru.setObjectName("luru")
        self.label_24 = QtWidgets.QLabel(self.page_2)
        self.label_24.setGeometry(QtCore.QRect(600, -10, 611, 591))
        self.label_24.setAutoFillBackground(False)
        self.label_24.setStyleSheet("")
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/img/背景.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(810, 310, 321, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.car_id_1 = LineEdit(self.gridLayoutWidget_2)
        self.car_id_1.setObjectName("car_id_1")
        self.gridLayout_2.addWidget(self.car_id_1, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 4, 0, 1, 1)
        self.out_time_1 = LineEdit(self.gridLayoutWidget_2)
        self.out_time_1.setObjectName("out_time_1")
        self.gridLayout_2.addWidget(self.out_time_1, 4, 2, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 0, 1, 1)
        self.get_time_1 = PushButton(self.gridLayoutWidget_2)
        self.get_time_1.setObjectName("get_time_1")
        self.gridLayout_2.addWidget(self.get_time_1, 4, 4, 1, 1)
        self.sel_car = PushButton(self.gridLayoutWidget_2)
        self.sel_car.setObjectName("sel_car")
        self.gridLayout_2.addWidget(self.sel_car, 1, 4, 1, 1)
        self.in_time_1 = LineEdit(self.gridLayoutWidget_2)
        self.in_time_1.setObjectName("in_time_1")
        self.gridLayout_2.addWidget(self.in_time_1, 2, 2, 1, 3)
        self.label_31 = QtWidgets.QLabel(self.page_2)
        self.label_31.setGeometry(QtCore.QRect(660, 70, 71, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(167, 173, 214);")
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.luru_2 = PushButton(self.page_2)
        self.luru_2.setGeometry(QtCore.QRect(130, 490, 301, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.luru_2.setFont(font)
        self.luru_2.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.luru_2.setObjectName("luru_2")
        self.dengji_1 = PushButton(self.page_2)
        self.dengji_1.setGeometry(QtCore.QRect(820, 490, 301, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.dengji_1.setFont(font)
        self.dengji_1.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.dengji_1.setObjectName("dengji_1")
        self.dengji = PushButton(self.page_2)
        self.dengji.setGeometry(QtCore.QRect(820, 220, 301, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.dengji.setFont(font)
        self.dengji.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.dengji.setObjectName("dengji")
        self.label_32 = QtWidgets.QLabel(self.page_2)
        self.label_32.setGeometry(QtCore.QRect(650, 330, 71, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(167, 173, 214);")
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(810, 60, 321, 151))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 3, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 0, 1, 1)
        self.in_time = LineEdit(self.gridLayoutWidget_3)
        self.in_time.setObjectName("in_time")
        self.gridLayout_3.addWidget(self.in_time, 3, 1, 1, 1)
        self.get_time = PushButton(self.gridLayoutWidget_3)
        self.get_time.setObjectName("get_time")
        self.gridLayout_3.addWidget(self.get_time, 3, 2, 1, 1)
        self.car_id = LineEdit(self.gridLayoutWidget_3)
        self.car_id.setObjectName("car_id")
        self.gridLayout_3.addWidget(self.car_id, 0, 1, 1, 2)
        self.label_24.raise_()
        self.label_18.raise_()
        self.label_11.raise_()
        self.gridLayoutWidget.raise_()
        self.luru.raise_()
        self.gridLayoutWidget_2.raise_()
        self.label_31.raise_()
        self.luru_2.raise_()
        self.dengji_1.raise_()
        self.dengji.raise_()
        self.label_32.raise_()
        self.gridLayoutWidget_3.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(50, 420, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(167, 173, 214);")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(840, 470, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(140, 420, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(140, 470, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(430, 470, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setGeometry(QtCore.QRect(430, 420, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(130, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.btnEdit = QtWidgets.QPushButton(self.page_3)
        self.btnEdit.setGeometry(QtCore.QRect(910, 60, 91, 31))
        self.btnEdit.setObjectName("btnEdit")
        self.btnQuery = QtWidgets.QPushButton(self.page_3)
        self.btnQuery.setGeometry(QtCore.QRect(750, 60, 91, 31))
        self.btnQuery.setObjectName("btnQuery")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(840, 420, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(450, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setGeometry(QtCore.QRect(0, -10, 1161, 571))
        self.label_17.setAutoFillBackground(False)
        self.label_17.setStyleSheet("")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/img/背景.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.cboxClass = ComboBox(self.page_3)
        self.cboxClass.setGeometry(QtCore.QRect(520, 60, 131, 32))
        self.cboxClass.setObjectName("cboxClass")
        self.cboxGrade = ComboBox(self.page_3)
        self.cboxGrade.setGeometry(QtCore.QRect(220, 60, 121, 32))
        self.cboxGrade.setObjectName("cboxGrade")
        self.editID = LineEdit(self.page_3)
        self.editID.setGeometry(QtCore.QRect(190, 410, 128, 33))
        self.editID.setObjectName("editID")
        self.editAge = LineEdit(self.page_3)
        self.editAge.setGeometry(QtCore.QRect(520, 460, 201, 33))
        self.editAge.setObjectName("editAge")
        self.editPhone = LineEdit(self.page_3)
        self.editPhone.setGeometry(QtCore.QRect(210, 460, 111, 33))
        self.editPhone.setObjectName("editPhone")
        self.editAddress = LineEdit(self.page_3)
        self.editAddress.setGeometry(QtCore.QRect(890, 410, 141, 33))
        self.editAddress.setObjectName("editAddress")
        self.editID_5 = LineEdit(self.page_3)
        self.editID_5.setGeometry(QtCore.QRect(90, 110, 128, 33))
        self.editID_5.setObjectName("editID_5")
        self.PushButton_21 = PushButton(self.page_3)
        self.PushButton_21.setGeometry(QtCore.QRect(120, 100, 931, 301))
        self.PushButton_21.setStyleSheet("PushButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 15px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"PushButton:disabled, {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"TransparentPushButton:pressed,\n"
"{\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"TransprentPushButton:disabled,")
        self.PushButton_21.setText("")
        self.PushButton_21.setObjectName("PushButton_21")
        self.wp_information_1 = TableWidget(self.page_3)
        self.wp_information_1.setGeometry(QtCore.QRect(160, 110, 841, 271))
        self.wp_information_1.setObjectName("wp_information_1")
        self.wp_information_1.setColumnCount(0)
        self.wp_information_1.setRowCount(0)
        self.editName = LineEdit(self.page_3)
        self.editName.setGeometry(QtCore.QRect(520, 410, 201, 33))
        self.editName.setObjectName("editName")
        self.cboxSex = LineEdit(self.page_3)
        self.cboxSex.setGeometry(QtCore.QRect(890, 460, 141, 33))
        self.cboxSex.setObjectName("cboxSex")
        self.editID_5.raise_()
        self.label_17.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.btnEdit.raise_()
        self.btnQuery.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.cboxClass.raise_()
        self.cboxGrade.raise_()
        self.editID.raise_()
        self.editAge.raise_()
        self.editPhone.raise_()
        self.editAddress.raise_()
        self.PushButton_21.raise_()
        self.wp_information_1.raise_()
        self.editName.raise_()
        self.cboxSex.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.SearchLineEdit = SearchLineEdit(self.page_4)
        self.SearchLineEdit.setGeometry(QtCore.QRect(910, 10, 187, 33))
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.PushButton = PushButton(self.page_4)
        self.PushButton.setGeometry(QtCore.QRect(1110, 10, 102, 32))
        self.PushButton.setObjectName("PushButton")
        self.search_1 = PushButton(self.page_4)
        self.search_1.setGeometry(QtCore.QRect(390, 50, 81, 32))
        self.search_1.setObjectName("search_1")
        self.PushButton_4 = PushButton(self.page_4)
        self.PushButton_4.setGeometry(QtCore.QRect(60, 50, 101, 32))
        self.PushButton_4.setStyleSheet("PushButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"PushButton:disabled, {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"TransparentPushButton:pressed,\n"
"{\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"TransprentPushButton:disabled,")
        self.PushButton_4.setObjectName("PushButton_4")
        self.PushButton_6 = PushButton(self.page_4)
        self.PushButton_6.setGeometry(QtCore.QRect(990, 70, 141, 32))
        self.PushButton_6.setStyleSheet("PushButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"PushButton:disabled, {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"TransparentPushButton:pressed,\n"
"{\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"TransprentPushButton:disabled,")
        self.PushButton_6.setObjectName("PushButton_6")
        self.PushButton_7 = PushButton(self.page_4)
        self.PushButton_7.setGeometry(QtCore.QRect(1010, 480, 121, 32))
        self.PushButton_7.setObjectName("PushButton_7")
        self.PushButton_9 = PushButton(self.page_4)
        self.PushButton_9.setGeometry(QtCore.QRect(890, 60, 321, 491))
        self.PushButton_9.setStyleSheet("PushButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 15px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"PushButton:disabled, {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"TransparentPushButton:pressed,\n"
"{\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"TransprentPushButton:disabled,")
        self.PushButton_9.setText("")
        self.PushButton_9.setObjectName("PushButton_9")
        self.PushButton_10 = PushButton(self.page_4)
        self.PushButton_10.setGeometry(QtCore.QRect(10, 30, 871, 531))
        self.PushButton_10.setStyleSheet("PushButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 15px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"PushButton:disabled, {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"TransparentPushButton:pressed,\n"
"{\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"TransprentPushButton:disabled,")
        self.PushButton_10.setText("")
        self.PushButton_10.setObjectName("PushButton_10")
        self.ZhDatePicker = ZhDatePicker(self.page_4)
        self.ZhDatePicker.setGeometry(QtCore.QRect(920, 360, 240, 30))
        self.ZhDatePicker.setObjectName("ZhDatePicker")
        self.locationID = LineEdit(self.page_4)
        self.locationID.setGeometry(QtCore.QRect(190, 50, 141, 33))
        self.locationID.setObjectName("locationID")
        self.PushButton_11 = PushButton(self.page_4)
        self.PushButton_11.setGeometry(QtCore.QRect(920, 310, 91, 32))
        self.PushButton_11.setStyleSheet("PushButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"PushButton:disabled, {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"TransparentPushButton:pressed,\n"
"{\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"TransprentPushButton:disabled,")
        self.PushButton_11.setObjectName("PushButton_11")
        self.PushButton_12 = PushButton(self.page_4)
        self.PushButton_12.setGeometry(QtCore.QRect(920, 210, 91, 32))
        self.PushButton_12.setStyleSheet("PushButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"PushButton:disabled, {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"TransparentPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"TransparentPushButton:pressed,\n"
"{\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"TransprentPushButton:disabled,")
        self.PushButton_12.setObjectName("PushButton_12")
        self.RadioButton = RadioButton(self.page_4)
        self.RadioButton.setGeometry(QtCore.QRect(950, 130, 113, 24))
        self.RadioButton.setObjectName("RadioButton")
        self.RadioButton_2 = RadioButton(self.page_4)
        self.RadioButton_2.setGeometry(QtCore.QRect(1080, 130, 113, 24))
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.SearchLineEdit_2 = SearchLineEdit(self.page_4)
        self.SearchLineEdit_2.setGeometry(QtCore.QRect(920, 260, 241, 33))
        self.SearchLineEdit_2.setObjectName("SearchLineEdit_2")
        self.TableWidget_3 = TableWidget(self.page_4)
        self.TableWidget_3.setGeometry(QtCore.QRect(30, 100, 831, 441))
        self.TableWidget_3.setObjectName("TableWidget_3")
        self.TableWidget_3.setColumnCount(0)
        self.TableWidget_3.setRowCount(0)
        self.PushButton_10.raise_()
        self.PushButton_9.raise_()
        self.SearchLineEdit.raise_()
        self.PushButton.raise_()
        self.search_1.raise_()
        self.PushButton_4.raise_()
        self.PushButton_6.raise_()
        self.PushButton_7.raise_()
        self.ZhDatePicker.raise_()
        self.locationID.raise_()
        self.PushButton_11.raise_()
        self.PushButton_12.raise_()
        self.RadioButton.raise_()
        self.RadioButton_2.raise_()
        self.SearchLineEdit_2.raise_()
        self.TableWidget_3.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_5)
        self.stackedWidget_2.setGeometry(QtCore.QRect(9, 20, 921, 500))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.MT_0 = QtWidgets.QWidget()
        self.MT_0.setObjectName("MT_0")
        self.shijian_fenbu = QtWidgets.QLabel(self.MT_0)
        self.shijian_fenbu.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.shijian_fenbu.setObjectName("shijian_fenbu")
        self.stackedWidget_2.addWidget(self.MT_0)
        self.MT_1 = QtWidgets.QWidget()
        self.MT_1.setObjectName("MT_1")
        self.zhoufanmang = QtWidgets.QLabel(self.MT_1)
        self.zhoufanmang.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.zhoufanmang.setObjectName("zhoufanmang")
        self.stackedWidget_2.addWidget(self.MT_1)
        self.MT_2 = QtWidgets.QWidget()
        self.MT_2.setObjectName("MT_2")
        self.fee = QtWidgets.QLabel(self.MT_2)
        self.fee.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.fee.setObjectName("fee")
        self.stackedWidget_2.addWidget(self.MT_2)
        self.MT_3 = QtWidgets.QWidget()
        self.MT_3.setObjectName("MT_3")
        self.gaofeng = QtWidgets.QLabel(self.MT_3)
        self.gaofeng.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.gaofeng.setObjectName("gaofeng")
        self.stackedWidget_2.addWidget(self.MT_3)
        self.MT_4 = QtWidgets.QWidget()
        self.MT_4.setObjectName("MT_4")
        self.jiedaitj = QtWidgets.QLabel(self.MT_4)
        self.jiedaitj.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.jiedaitj.setObjectName("jiedaitj")
        self.stackedWidget_2.addWidget(self.MT_4)
        self.QT_0 = QtWidgets.QWidget()
        self.QT_0.setObjectName("QT_0")
        self.web_0 = QtWebEngineWidgets.QWebEngineView(self.QT_0)
        self.web_0.setGeometry(QtCore.QRect(0, 0, 921, 501))
        self.web_0.setObjectName("web_0")
        self.stackedWidget_2.addWidget(self.QT_0)
        self.QT_1 = QtWidgets.QWidget()
        self.QT_1.setObjectName("QT_1")
        self.stackedWidget_2.addWidget(self.QT_1)
        self.PushButton_25 = PushButton(self.page_5)
        self.PushButton_25.setGeometry(QtCore.QRect(-2, 1, 1221, 561))
        self.PushButton_25.setStyleSheet("PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"")
        self.PushButton_25.setText("")
        self.PushButton_25.setObjectName("PushButton_25")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1020, 20, 160, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shijian_fenbu_2 = PushButton(self.verticalLayoutWidget)
        self.shijian_fenbu_2.setObjectName("shijian_fenbu_2")
        self.verticalLayout_2.addWidget(self.shijian_fenbu_2)
        self.zhoufanmang_2 = PushButton(self.verticalLayoutWidget)
        self.zhoufanmang_2.setObjectName("zhoufanmang_2")
        self.verticalLayout_2.addWidget(self.zhoufanmang_2)
        self.fee_2 = PushButton(self.verticalLayoutWidget)
        self.fee_2.setObjectName("fee_2")
        self.verticalLayout_2.addWidget(self.fee_2)
        self.gaofeng_2 = PushButton(self.verticalLayoutWidget)
        self.gaofeng_2.setObjectName("gaofeng_2")
        self.verticalLayout_2.addWidget(self.gaofeng_2)
        self.jiedai = PushButton(self.verticalLayoutWidget)
        self.jiedai.setObjectName("jiedai")
        self.verticalLayout_2.addWidget(self.jiedai)
        self.ciyun = PushButton(self.verticalLayoutWidget)
        self.ciyun.setObjectName("ciyun")
        self.verticalLayout_2.addWidget(self.ciyun)
        self.shiduan = PushButton(self.verticalLayoutWidget)
        self.shiduan.setObjectName("shiduan")
        self.verticalLayout_2.addWidget(self.shiduan)
        self.zonghe_2 = PushButton(self.verticalLayoutWidget)
        self.zonghe_2.setObjectName("zonghe_2")
        self.verticalLayout_2.addWidget(self.zonghe_2)
        self.zonghe_3 = PushButton(self.verticalLayoutWidget)
        self.zonghe_3.setObjectName("zonghe_3")
        self.verticalLayout_2.addWidget(self.zonghe_3)
        self.PushButton_25.raise_()
        self.stackedWidget_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.PillPushButton = PillPushButton(self.page_6)
        self.PillPushButton.setGeometry(QtCore.QRect(290, 130, 122, 30))
        self.PillPushButton.setObjectName("PillPushButton")
        self.stackedWidget.addWidget(self.page_6)
        wuqixinxi.setCentralWidget(self.centralwidget)

        self.retranslateUi(wuqixinxi)
        self.stackedWidget.setCurrentIndex(5)
        self.stackedWidget_2.setCurrentIndex(6)
        self.PushButton_8.clicked.connect(wuqixinxi.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wuqixinxi)

    def retranslateUi(self, wuqixinxi):
        _translate = QtCore.QCoreApplication.translate
        wuqixinxi.setWindowTitle(_translate("wuqixinxi", "智能停车场数据管理系统"))
        self.zhgl.setText(_translate("wuqixinxi", "账户管理"))
        self.wqtj.setText(_translate("wuqixinxi", "车位统计"))
        self.crkgl.setText(_translate("wuqixinxi", "人工出入管理"))
        self.qzxx.setText(_translate("wuqixinxi", "数据预览"))
        self.whby.setText(_translate("wuqixinxi", "车场现状"))
        self.qywqxx.setText(_translate("wuqixinxi", "数据分析"))
        self.afgl.setText(_translate("wuqixinxi", "待定"))
        self.PushButton_8.setText(_translate("wuqixinxi", "退出"))
        self.genggai.setText(_translate("wuqixinxi", "更改账户"))
        self.label_2.setText(_translate("wuqixinxi", "TextLabel"))
        self.zhuce.setText(_translate("wuqixinxi", "注    册"))
        self.TitleLabel.setText(_translate("wuqixinxi", "车位概览"))
        self.SubtitleLabel.setText(_translate("wuqixinxi", "总车位："))
        self.bq.setText(_translate("wuqixinxi", "剩余车位："))
        self.SubtitleLabel_4.setText(_translate("wuqixinxi", "占用车位："))
        self.wqtj_2.setText(_translate("wuqixinxi", "车位统计"))
        self.label_11.setText(_translate("wuqixinxi", "停车历史信息录入"))
        self.label_20.setText(_translate("wuqixinxi", "进入日期"))
        self.label_23.setText(_translate("wuqixinxi", "驶出日期"))
        self.label_22.setText(_translate("wuqixinxi", "驶出时间"))
        self.label_12.setText(_translate("wuqixinxi", "星期"))
        self.label_19.setText(_translate("wuqixinxi", "编号："))
        self.label_21.setText(_translate("wuqixinxi", "进入时间"))
        self.luru.setText(_translate("wuqixinxi", "录    入"))
        self.label_28.setText(_translate("wuqixinxi", "驶入时间"))
        self.label_25.setText(_translate("wuqixinxi", "驶出时间"))
        self.out_time_1.setText(_translate("wuqixinxi", "右侧获取时间"))
        self.label_27.setText(_translate("wuqixinxi", "编号："))
        self.get_time_1.setText(_translate("wuqixinxi", "获取"))
        self.sel_car.setText(_translate("wuqixinxi", "搜索"))
        self.label_31.setText(_translate("wuqixinxi", "车辆驶入登记"))
        self.luru_2.setText(_translate("wuqixinxi", "获取当前时间"))
        self.dengji_1.setText(_translate("wuqixinxi", "登      记"))
        self.dengji.setText(_translate("wuqixinxi", "登      记"))
        self.label_32.setText(_translate("wuqixinxi", "车辆驶出登记"))
        self.label_30.setText(_translate("wuqixinxi", "驶入时间"))
        self.label_29.setText(_translate("wuqixinxi", "编号："))
        self.in_time.setText(_translate("wuqixinxi", "右侧获取时间"))
        self.get_time.setText(_translate("wuqixinxi", "获取"))
        self.label_6.setText(_translate("wuqixinxi", "车辆信息"))
        self.label_9.setText(_translate("wuqixinxi", "时段"))
        self.label_7.setText(_translate("wuqixinxi", "车牌号："))
        self.label_8.setText(_translate("wuqixinxi", "停留时间"))
        self.label_10.setText(_translate("wuqixinxi", "驶出时间"))
        self.label_13.setText(_translate("wuqixinxi", "驶入时间"))
        self.label_14.setText(_translate("wuqixinxi", "星期"))
        self.btnEdit.setText(_translate("wuqixinxi", "修改"))
        self.btnQuery.setText(_translate("wuqixinxi", "刷新"))
        self.label_15.setText(_translate("wuqixinxi", "星期"))
        self.label_16.setText(_translate("wuqixinxi", "时段"))
        self.PushButton.setText(_translate("wuqixinxi", "搜索"))
        self.search_1.setText(_translate("wuqixinxi", "查询"))
        self.PushButton_4.setText(_translate("wuqixinxi", "编号"))
        self.PushButton_6.setText(_translate("wuqixinxi", "维护保养登记"))
        self.PushButton_7.setText(_translate("wuqixinxi", "录入"))
        self.PushButton_11.setText(_translate("wuqixinxi", "日期"))
        self.PushButton_12.setText(_translate("wuqixinxi", "编号/柜号"))
        self.RadioButton.setText(_translate("wuqixinxi", "单个"))
        self.RadioButton_2.setText(_translate("wuqixinxi", "批量"))
        self.shijian_fenbu.setText(_translate("wuqixinxi", "TextLabel"))
        self.zhoufanmang.setText(_translate("wuqixinxi", "TextLabel"))
        self.fee.setText(_translate("wuqixinxi", "TextLabel"))
        self.gaofeng.setText(_translate("wuqixinxi", "TextLabel"))
        self.jiedaitj.setText(_translate("wuqixinxi", "TextLabel"))
        self.shijian_fenbu_2.setText(_translate("wuqixinxi", "停车时间分布"))
        self.zhoufanmang_2.setText(_translate("wuqixinxi", "周繁忙统计"))
        self.fee_2.setText(_translate("wuqixinxi", "收入分析"))
        self.gaofeng_2.setText(_translate("wuqixinxi", "停车时段统计"))
        self.jiedai.setText(_translate("wuqixinxi", "接待车辆统计"))
        self.ciyun.setText(_translate("wuqixinxi", "词云-web"))
        self.shiduan.setText(_translate("wuqixinxi", "时段-web"))
        self.zonghe_2.setText(_translate("wuqixinxi", "综合分析-web"))
        self.zonghe_3.setText(_translate("wuqixinxi", "收入分析-web"))
        self.PillPushButton.setText(_translate("wuqixinxi", "Pill push button"))
from PyQt5 import QtWebEngineWidgets
from qfluentwidgets import ComboBox, LineEdit, PasswordLineEdit, PillPushButton, PrimaryPushButton, PushButton, RadioButton, SearchLineEdit, SubtitleLabel, TableWidget, TimePicker, TitleLabel, ZhDatePicker
