# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wuqixinxi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_wuqixinxi(object):
    def setupUi(self, wuqixinxi):
        wuqixinxi.setObjectName("wuqixinxi")
        wuqixinxi.resize(1467, 807)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/院徽.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        wuqixinxi.setWindowIcon(icon)
        wuqixinxi.setStyleSheet("QWidget#centralwidget{\n"
"    border-image: url(:/img/主界面背景.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(wuqixinxi)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_backgroung = QtWidgets.QWidget(self.centralwidget)
        self.widget_backgroung.setStyleSheet("/*QWidget#widget_backgroung{\n"
"    border-image: url(:/img/主界面背景.png);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}*/")
        self.widget_backgroung.setObjectName("widget_backgroung")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_backgroung)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.widget_backgroung)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(90, 90))
        self.label.setMaximumSize(QtCore.QSize(90, 90))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/院徽.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_backgroung)
        self.widget_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_23 = QtWidgets.QWidget(self.widget_3)
        self.widget_23.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(230, 232, 236);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:12px;\n"
"border-image: url(:/img/btn2.png);\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"border:3px solid rgb(230, 232, 236);\n"
"}")
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout.setObjectName("verticalLayout")
        self.zhgl = QtWidgets.QPushButton(self.widget_23)
        self.zhgl.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.zhgl.setFont(font)
        self.zhgl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zhgl.setAutoFillBackground(False)
        self.zhgl.setStyleSheet("")
        self.zhgl.setObjectName("zhgl")
        self.verticalLayout.addWidget(self.zhgl)
        self.wqtj = QtWidgets.QPushButton(self.widget_23)
        self.wqtj.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.wqtj.setFont(font)
        self.wqtj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wqtj.setObjectName("wqtj")
        self.verticalLayout.addWidget(self.wqtj)
        self.crkgl = QtWidgets.QPushButton(self.widget_23)
        self.crkgl.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.crkgl.setFont(font)
        self.crkgl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.crkgl.setObjectName("crkgl")
        self.verticalLayout.addWidget(self.crkgl)
        self.qzxx = QtWidgets.QPushButton(self.widget_23)
        self.qzxx.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.qzxx.setFont(font)
        self.qzxx.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qzxx.setObjectName("qzxx")
        self.verticalLayout.addWidget(self.qzxx)
        self.whby = QtWidgets.QPushButton(self.widget_23)
        self.whby.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.whby.setFont(font)
        self.whby.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.whby.setObjectName("whby")
        self.verticalLayout.addWidget(self.whby)
        self.qywqxx = QtWidgets.QPushButton(self.widget_23)
        self.qywqxx.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.qywqxx.setFont(font)
        self.qywqxx.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qywqxx.setObjectName("qywqxx")
        self.verticalLayout.addWidget(self.qywqxx)
        self.afgl = QtWidgets.QPushButton(self.widget_23)
        self.afgl.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.afgl.setFont(font)
        self.afgl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.afgl.setObjectName("afgl")
        self.verticalLayout.addWidget(self.afgl)
        self.PushButton_8 = QtWidgets.QPushButton(self.widget_23)
        self.PushButton_8.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.PushButton_8.setFont(font)
        self.PushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButton_8.setObjectName("PushButton_8")
        self.verticalLayout.addWidget(self.PushButton_8)
        spacerItem2 = QtWidgets.QSpacerItem(200, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.widget_23)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setStyleSheet("QWidget#widget_4,QWidget#widget_5,QWidget#widget_6,QWidget#widget_7,QWidget#widget_8{\n"
"border-radius:5px;\n"
"border:1px solid rgb(1, 182, 215);\n"
"}\n"
"QLineEdit{\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 246, 255);\n"
"}\n"
"QWidget#page_0{\n"
"border-image: url(:/img/bj4.png);\n"
"}")
        self.page_0.setObjectName("page_0")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_39 = QtWidgets.QLabel(self.page_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setMinimumSize(QtCore.QSize(0, 100))
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 0, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.page_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.widget_9)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(1, 182, 215);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.name_1 = LineEdit(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_1.sizePolicy().hasHeightForWidth())
        self.name_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        self.name_1.setFont(font)
        self.name_1.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.name_1.setText("")
        self.name_1.setObjectName("name_1")
        self.horizontalLayout_4.addWidget(self.name_1)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_9)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_26 = QtWidgets.QLabel(self.widget_5)
        self.label_26.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(1, 182, 215);")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_5.addWidget(self.label_26)
        self.ps_3 = PasswordLineEdit(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ps_3.sizePolicy().hasHeightForWidth())
        self.ps_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.ps_3.setFont(font)
        self.ps_3.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.ps_3.setText("")
        self.ps_3.setObjectName("ps_3")
        self.horizontalLayout_5.addWidget(self.ps_3)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_9)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_33 = QtWidgets.QLabel(self.widget_6)
        self.label_33.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(1, 182, 215);")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_6.addWidget(self.label_33)
        self.name_2 = LineEdit(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_2.sizePolicy().hasHeightForWidth())
        self.name_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.name_2.setFont(font)
        self.name_2.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.name_2.setText("")
        self.name_2.setObjectName("name_2")
        self.horizontalLayout_6.addWidget(self.name_2)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_9)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_34 = QtWidgets.QLabel(self.widget_7)
        self.label_34.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(1, 182, 215);")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_7.addWidget(self.label_34)
        self.ps_2 = PasswordLineEdit(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ps_2.sizePolicy().hasHeightForWidth())
        self.ps_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.ps_2.setFont(font)
        self.ps_2.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.ps_2.setText("")
        self.ps_2.setObjectName("ps_2")
        self.horizontalLayout_7.addWidget(self.ps_2)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_9)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_8.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_35 = QtWidgets.QLabel(self.widget_8)
        self.label_35.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(1, 182, 215);")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_8.addWidget(self.label_35)
        self.ps_1 = PasswordLineEdit(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ps_1.sizePolicy().hasHeightForWidth())
        self.ps_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.ps_1.setFont(font)
        self.ps_1.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: white; /* 修改文本颜色为白色 */\n"
"    background-color: transparent; /* 修改背景为透明 */\n"
"    border: none; /* 移除边框以达到透明效果 */\n"
"    /* border-bottom: 1px solid rgba(0, 0, 0, 100); 去掉底部边框 */\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"\n"
"\n"
"LineEdit:focus,\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border: none;\n"
"    \n"
"}\n"
"\n"
"/* 禁用状态的颜色也需要相应调整 */\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(255, 255, 255, 0.5); /* 文本颜色调整为半透明白色 */\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.ps_1.setText("")
        self.ps_1.setObjectName("ps_1")
        self.horizontalLayout_8.addWidget(self.ps_1)
        self.verticalLayout_4.addWidget(self.widget_8)
        self.genggai = QtWidgets.QPushButton(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genggai.sizePolicy().hasHeightForWidth())
        self.genggai.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.genggai.setFont(font)
        self.genggai.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.genggai.setObjectName("genggai")
        self.verticalLayout_4.addWidget(self.genggai)
        self.zhuce = QtWidgets.QPushButton(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zhuce.sizePolicy().hasHeightForWidth())
        self.zhuce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.zhuce.setFont(font)
        self.zhuce.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.zhuce.setObjectName("zhuce")
        self.verticalLayout_4.addWidget(self.zhuce)
        self.gridLayout_4.addWidget(self.widget_9, 1, 1, 3, 1)
        self.label_40 = QtWidgets.QLabel(self.page_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setMinimumSize(QtCore.QSize(0, 100))
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 4, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.page_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setMinimumSize(QtCore.QSize(0, 100))
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 2, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.page_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMinimumSize(QtCore.QSize(0, 100))
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 2, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 20)
        self.gridLayout_4.setColumnStretch(1, 20)
        self.gridLayout_4.setColumnStretch(2, 20)
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("QWidget#page_1{\n"
"border-image: url(:/img/bj4.png);\n"
"}")
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_11 = QtWidgets.QWidget(self.page_1)
        self.widget_11.setStyleSheet("")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_5.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_11)
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widget.setObjectName("widget")
        self.widget_10 = QtWidgets.QWidget(self.widget)
        self.widget_10.setGeometry(QtCore.QRect(0, 0, 551, 296))
        self.widget_10.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}\n"
"")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TitleLabel = TitleLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setStyleSheet("")
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_5.addWidget(self.TitleLabel, 0, 0, 1, 2)
        self.SubtitleLabel = SubtitleLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.SubtitleLabel.setFont(font)
        self.SubtitleLabel.setStyleSheet("")
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout_5.addWidget(self.SubtitleLabel, 1, 0, 1, 1)
        self.SubtitleLabel_4 = SubtitleLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.SubtitleLabel_4.setFont(font)
        self.SubtitleLabel_4.setStyleSheet("")
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.gridLayout_5.addWidget(self.SubtitleLabel_4, 2, 0, 1, 1)
        self.bq = SubtitleLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(13)
        self.bq.setFont(font)
        self.bq.setStyleSheet("")
        self.bq.setObjectName("bq")
        self.gridLayout_5.addWidget(self.bq, 2, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.widget)
        self.horizontalLayout_10.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.page_1)
        self.widget_12.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}\n"
"")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_9.setContentsMargins(25, 25, 25, 25)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_21 = QtWebEngineWidgets.QWebEngineView(self.widget_12)
        self.widget_21.page().setBackgroundColor(Qt.transparent)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_9.addWidget(self.widget_21)
        self.horizontalLayout_10.addWidget(self.widget_12)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QWidget#page_2{\n"
"border-image: url(:/img/bj4.png);\n"
"}\n"
"")
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_13 = QtWidgets.QWidget(self.page_2)
        self.widget_13.setStyleSheet("")
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.label_24 = QtWidgets.QLabel(self.widget_13)
        self.label_24.setMinimumSize(QtCore.QSize(60, 0))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.widget_17 = QtWidgets.QWidget(self.widget_13)
        self.widget_17.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.widget_17.setObjectName("widget_17")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_17)
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 0, 1, 1)
        self.TimePicker_2 = TimePicker(self.widget_17)
        self.TimePicker_2.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.TimePicker_2.setFont(font)
        self.TimePicker_2.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"")
        self.TimePicker_2.setObjectName("TimePicker_2")
        self.gridLayout.addWidget(self.TimePicker_2, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("")
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 0, 1, 1)
        self.editID_2 = LineEdit(self.widget_17)
        self.editID_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.editID_2.setFont(font)
        self.editID_2.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.editID_2.setObjectName("editID_2")
        self.gridLayout.addWidget(self.editID_2, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)
        self.TimePicker = TimePicker(self.widget_17)
        self.TimePicker.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.TimePicker.setFont(font)
        self.TimePicker.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"")
        self.TimePicker.setText("")
        self.TimePicker.setObjectName("TimePicker")
        self.gridLayout.addWidget(self.TimePicker, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.editAddress_2 = LineEdit(self.widget_17)
        self.editAddress_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.editAddress_2.setFont(font)
        self.editAddress_2.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.editAddress_2.setObjectName("editAddress_2")
        self.gridLayout.addWidget(self.editAddress_2, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)
        self.ZhDatePicker_2 = ZhDatePicker(self.widget_17)
        self.ZhDatePicker_2.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.ZhDatePicker_2.setFont(font)
        self.ZhDatePicker_2.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"")
        self.ZhDatePicker_2.setText("")
        self.ZhDatePicker_2.setObjectName("ZhDatePicker_2")
        self.gridLayout.addWidget(self.ZhDatePicker_2, 1, 1, 1, 1)
        self.ZhDatePicker_3 = ZhDatePicker(self.widget_17)
        self.ZhDatePicker_3.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.ZhDatePicker_3.setFont(font)
        self.ZhDatePicker_3.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"")
        self.ZhDatePicker_3.setText("")
        self.ZhDatePicker_3.setObjectName("ZhDatePicker_3")
        self.gridLayout.addWidget(self.ZhDatePicker_3, 3, 1, 1, 1)
        self.luru = QtWidgets.QPushButton(self.widget_17)
        self.luru.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.luru.setFont(font)
        self.luru.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.luru.setObjectName("luru")
        self.gridLayout.addWidget(self.luru, 6, 0, 1, 2)
        self.luru_2 = QtWidgets.QPushButton(self.widget_17)
        self.luru_2.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.luru_2.setFont(font)
        self.luru_2.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.luru_2.setObjectName("luru_2")
        self.gridLayout.addWidget(self.luru_2, 7, 0, 1, 2)
        self.horizontalLayout_11.addWidget(self.widget_17)
        self.label_36 = QtWidgets.QLabel(self.widget_13)
        self.label_36.setMinimumSize(QtCore.QSize(60, 0))
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_11.addWidget(self.label_36)
        self.horizontalLayout_14.addWidget(self.widget_13)
        self.widget_16 = QtWidgets.QWidget(self.page_2)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_14 = QtWidgets.QWidget(self.widget_16)
        self.widget_14.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_31 = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_12.addWidget(self.label_31)
        self.label_2 = QtWidgets.QLabel(self.widget_14)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_29 = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 0, 1, 1)
        self.car_id = LineEdit(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_id.sizePolicy().hasHeightForWidth())
        self.car_id.setSizePolicy(sizePolicy)
        self.car_id.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.car_id.setFont(font)
        self.car_id.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.car_id.setObjectName("car_id")
        self.gridLayout_3.addWidget(self.car_id, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 1, 0, 1, 1)
        self.in_time = LineEdit(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_time.sizePolicy().hasHeightForWidth())
        self.in_time.setSizePolicy(sizePolicy)
        self.in_time.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.in_time.setFont(font)
        self.in_time.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.in_time.setObjectName("in_time")
        self.gridLayout_3.addWidget(self.in_time, 1, 1, 1, 1)
        self.dengji = QtWidgets.QPushButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dengji.sizePolicy().hasHeightForWidth())
        self.dengji.setSizePolicy(sizePolicy)
        self.dengji.setMinimumSize(QtCore.QSize(365, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.dengji.setFont(font)
        self.dengji.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.dengji.setObjectName("dengji")
        self.gridLayout_3.addWidget(self.dengji, 2, 0, 1, 3)
        self.get_time = QtWidgets.QPushButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_time.sizePolicy().hasHeightForWidth())
        self.get_time.setSizePolicy(sizePolicy)
        self.get_time.setMinimumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.get_time.setFont(font)
        self.get_time.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.get_time.setObjectName("get_time")
        self.gridLayout_3.addWidget(self.get_time, 1, 2, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout_3)
        self.label_4 = QtWidgets.QLabel(self.widget_14)
        self.label_4.setMinimumSize(QtCore.QSize(60, 0))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.verticalLayout_7.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.widget_16)
        self.widget_15.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_32 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_13.addWidget(self.label_32)
        self.label_18 = QtWidgets.QLabel(self.widget_15)
        self.label_18.setMinimumSize(QtCore.QSize(60, 0))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_27 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 0, 0, 1, 1)
        self.car_id_1 = LineEdit(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_id_1.sizePolicy().hasHeightForWidth())
        self.car_id_1.setSizePolicy(sizePolicy)
        self.car_id_1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.car_id_1.setFont(font)
        self.car_id_1.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.car_id_1.setObjectName("car_id_1")
        self.gridLayout_2.addWidget(self.car_id_1, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 1, 0, 1, 1)
        self.in_time_1 = LineEdit(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_time_1.sizePolicy().hasHeightForWidth())
        self.in_time_1.setSizePolicy(sizePolicy)
        self.in_time_1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.in_time_1.setFont(font)
        self.in_time_1.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.in_time_1.setObjectName("in_time_1")
        self.gridLayout_2.addWidget(self.in_time_1, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 2, 0, 1, 1)
        self.out_time_1 = LineEdit(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_time_1.sizePolicy().hasHeightForWidth())
        self.out_time_1.setSizePolicy(sizePolicy)
        self.out_time_1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.out_time_1.setFont(font)
        self.out_time_1.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.out_time_1.setObjectName("out_time_1")
        self.gridLayout_2.addWidget(self.out_time_1, 2, 1, 1, 1)
        self.get_time_1 = QtWidgets.QPushButton(self.widget_15)
        self.get_time_1.setMinimumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.get_time_1.setFont(font)
        self.get_time_1.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.get_time_1.setObjectName("get_time_1")
        self.gridLayout_2.addWidget(self.get_time_1, 2, 2, 1, 1)
        self.sel_car = QtWidgets.QPushButton(self.widget_15)
        self.sel_car.setMinimumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.sel_car.setFont(font)
        self.sel_car.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.sel_car.setObjectName("sel_car")
        self.gridLayout_2.addWidget(self.sel_car, 0, 2, 1, 1)
        self.dengji_1 = QtWidgets.QPushButton(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dengji_1.sizePolicy().hasHeightForWidth())
        self.dengji_1.setSizePolicy(sizePolicy)
        self.dengji_1.setMinimumSize(QtCore.QSize(365, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        self.dengji_1.setFont(font)
        self.dengji_1.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :10px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.dengji_1.setObjectName("dengji_1")
        self.gridLayout_2.addWidget(self.dengji_1, 3, 0, 1, 3)
        self.horizontalLayout_13.addLayout(self.gridLayout_2)
        self.label_5 = QtWidgets.QLabel(self.widget_15)
        self.label_5.setMinimumSize(QtCore.QSize(60, 0))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.verticalLayout_7.addWidget(self.widget_15)
        self.horizontalLayout_14.addWidget(self.widget_16)
        self.horizontalLayout_14.setStretch(0, 10)
        self.horizontalLayout_14.setStretch(1, 10)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("QWidget#page_3{\n"
"border-image: url(:/img/bj4.png);\n"
"}\n"
"")
        self.page_3.setObjectName("page_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_18 = QtWidgets.QWidget(self.page_3)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.cboxGrade = ComboBox(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboxGrade.sizePolicy().hasHeightForWidth())
        self.cboxGrade.setSizePolicy(sizePolicy)
        self.cboxGrade.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.cboxGrade.setFont(font)
        self.cboxGrade.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.cboxGrade.setText("")
        self.cboxGrade.setObjectName("cboxGrade")
        self.horizontalLayout_15.addWidget(self.cboxGrade)
        self.label_16 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.cboxClass = ComboBox(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboxClass.sizePolicy().hasHeightForWidth())
        self.cboxClass.setSizePolicy(sizePolicy)
        self.cboxClass.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.cboxClass.setFont(font)
        self.cboxClass.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.cboxClass.setText("")
        self.cboxClass.setObjectName("cboxClass")
        self.horizontalLayout_15.addWidget(self.cboxClass)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.btnQuery = QtWidgets.QPushButton(self.widget_18)
        self.btnQuery.setMinimumSize(QtCore.QSize(91, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.btnQuery.setFont(font)
        self.btnQuery.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.btnQuery.setObjectName("btnQuery")
        self.horizontalLayout_15.addWidget(self.btnQuery)
        self.btnEdit = QtWidgets.QPushButton(self.widget_18)
        self.btnEdit.setMinimumSize(QtCore.QSize(91, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.btnEdit.setFont(font)
        self.btnEdit.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout_15.addWidget(self.btnEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.wp_information_1 = TableWidget(self.widget_18)
        self.wp_information_1.setStyleSheet("QTableView {\n"
"    background: transparent;\n"
"    outline: none;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"QTableView::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"QTableView::indicator:hover {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"QTableView::indicator:pressed {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"QTableView::indicator:checked,\n"
"QTableView::indicator:indeterminate {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"QTableView::indicator:checked {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    image: url(:/qfluentwidgets/images/check_box/Accept_white.svg);\n"
"}\n"
"\n"
"QTableView::indicator:indeterminate {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    image: url(:/qfluentwidgets/images/check_box/PartialAccept_white.svg);\n"
"}\n"
"\n"
"QTableView::indicator:checked:hover,\n"
"QTableView::indicator:indeterminate:hover {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"QTableView::indicator:checked:pressed,\n"
"QTableView::indicator:indeterminate:pressed {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"QTableView::indicator:disabled {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView::indicator:checked:disabled,\n"
"QTableView::indicator:indeterminate:disabled {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}\n"
"\n"
"\n"
"QHeaderView {\n"
"    background-color: transparent;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    background-color: transparent;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 19);\n"
"    font: 13px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 7);\n"
"    border-left: none;\n"
"    height: 40px;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal:last {\n"
"    border-right: none;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Down_black.svg);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Up_black.svg);\n"
"}\n"
"QTableCornerButton::section {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 19);\n"
"}\n"
"\n"
"QTableCornerButton::section:pressed {\n"
"    background-color: rgba(0, 0, 0, 12);\n"
"}")
        self.wp_information_1.setObjectName("wp_information_1")
        self.wp_information_1.setColumnCount(0)
        self.wp_information_1.setRowCount(0)
        self.wp_information_1.horizontalHeader().setStretchLastSection(False)
        self.wp_information_1.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.wp_information_1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_16.addWidget(self.label_6)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.editID = LineEdit(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editID.sizePolicy().hasHeightForWidth())
        self.editID.setSizePolicy(sizePolicy)
        self.editID.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.editID.setFont(font)
        self.editID.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.editID.setText("")
        self.editID.setObjectName("editID")
        self.gridLayout_6.addWidget(self.editID, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 2, 1, 1)
        self.editName = LineEdit(self.widget_18)
        self.editName.setMinimumSize(QtCore.QSize(201, 33))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.editName.setFont(font)
        self.editName.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.editName.setText("")
        self.editName.setObjectName("editName")
        self.gridLayout_6.addWidget(self.editName, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 4, 1, 1)
        self.editAddress = LineEdit(self.widget_18)
        self.editAddress.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.editAddress.setFont(font)
        self.editAddress.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.editAddress.setObjectName("editAddress")
        self.gridLayout_6.addWidget(self.editAddress, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.editPhone = LineEdit(self.widget_18)
        self.editPhone.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.editPhone.setFont(font)
        self.editPhone.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.editPhone.setText("")
        self.editPhone.setObjectName("editPhone")
        self.gridLayout_6.addWidget(self.editPhone, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 1, 2, 1, 1)
        self.editAge = LineEdit(self.widget_18)
        self.editAge.setMinimumSize(QtCore.QSize(201, 33))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.editAge.setFont(font)
        self.editAge.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.editAge.setText("")
        self.editAge.setObjectName("editAge")
        self.gridLayout_6.addWidget(self.editAge, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 1, 4, 1, 1)
        self.cboxSex = LineEdit(self.widget_18)
        self.cboxSex.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.cboxSex.setFont(font)
        self.cboxSex.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.cboxSex.setObjectName("cboxSex")
        self.gridLayout_6.addWidget(self.cboxSex, 1, 5, 1, 1)
        self.horizontalLayout_16.addLayout(self.gridLayout_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.verticalLayout_10.addWidget(self.widget_18)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("QWidget#page_4{\n"
"border-image: url(:/img/bj4.png);\n"
"}\n"
"")
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.widget_19 = QtWidgets.QWidget(self.page_4)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.PushButton_4 = QtWidgets.QPushButton(self.widget_19)
        self.PushButton_4.setMinimumSize(QtCore.QSize(101, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.PushButton_4.setFont(font)
        self.PushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.PushButton_4.setObjectName("PushButton_4")
        self.horizontalLayout_17.addWidget(self.PushButton_4)
        self.locationID = LineEdit(self.widget_19)
        self.locationID.setMinimumSize(QtCore.QSize(141, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.locationID.setFont(font)
        self.locationID.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.locationID.setText("")
        self.locationID.setObjectName("locationID")
        self.horizontalLayout_17.addWidget(self.locationID)
        self.search_1 = QtWidgets.QPushButton(self.widget_19)
        self.search_1.setMinimumSize(QtCore.QSize(101, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.search_1.setFont(font)
        self.search_1.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.search_1.setObjectName("search_1")
        self.horizontalLayout_17.addWidget(self.search_1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.TableWidget_3 = TableWidget(self.widget_19)
        self.TableWidget_3.setStyleSheet("QTableView {\n"
"    background: transparent;\n"
"    outline: none;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"QTableView::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"QTableView::indicator:hover {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"QTableView::indicator:pressed {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"QTableView::indicator:checked,\n"
"QTableView::indicator:indeterminate {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"QTableView::indicator:checked {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    image: url(:/qfluentwidgets/images/check_box/Accept_white.svg);\n"
"}\n"
"\n"
"QTableView::indicator:indeterminate {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    image: url(:/qfluentwidgets/images/check_box/PartialAccept_white.svg);\n"
"}\n"
"\n"
"QTableView::indicator:checked:hover,\n"
"QTableView::indicator:indeterminate:hover {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"QTableView::indicator:checked:pressed,\n"
"QTableView::indicator:indeterminate:pressed {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"QTableView::indicator:disabled {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView::indicator:checked:disabled,\n"
"QTableView::indicator:indeterminate:disabled {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}\n"
"\n"
"\n"
"QHeaderView {\n"
"    background-color: transparent;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    background-color: transparent;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 19);\n"
"    font: 13px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 7);\n"
"    border-left: none;\n"
"    height: 40px;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal:last {\n"
"    border-right: none;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Down_black.svg);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Up_black.svg);\n"
"}\n"
"QTableCornerButton::section {\n"
"color: rgb(1, 182, 215); /* 确保子元素的字体颜色也是蓝色 */\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 19);\n"
"}\n"
"\n"
"QTableCornerButton::section:pressed {\n"
"    background-color: rgba(0, 0, 0, 12);\n"
"}")
        self.TableWidget_3.setObjectName("TableWidget_3")
        self.TableWidget_3.setColumnCount(0)
        self.TableWidget_3.setRowCount(0)
        self.verticalLayout_8.addWidget(self.TableWidget_3)
        self.horizontalLayout_23.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.page_4)
        self.widget_20.setStyleSheet("QLabel{\n"
"color: rgb(1, 182, 215);\n"
"}")
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_28 = QtWidgets.QWidget(self.widget_20)
        self.widget_28.setMinimumSize(QtCore.QSize(0, 33))
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_9.addWidget(self.widget_28)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.SearchLineEdit = SearchLineEdit(self.widget_20)
        self.SearchLineEdit.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.SearchLineEdit.setFont(font)
        self.SearchLineEdit.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.horizontalLayout_18.addWidget(self.SearchLineEdit)
        self.PushButton = QtWidgets.QPushButton(self.widget_20)
        self.PushButton.setMinimumSize(QtCore.QSize(101, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.PushButton.setFont(font)
        self.PushButton.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout_18.addWidget(self.PushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.widget_24 = QtWidgets.QWidget(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_9.addWidget(self.widget_24)
        self.label_38 = QtWidgets.QLabel(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_9.addWidget(self.label_38)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.RadioButton = QtWidgets.QRadioButton(self.widget_20)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.RadioButton.setFont(font)
        self.RadioButton.setStyleSheet("color: rgb(1, 182, 215);")
        self.RadioButton.setObjectName("RadioButton")
        self.horizontalLayout_19.addWidget(self.RadioButton)
        self.RadioButton_2 = QtWidgets.QRadioButton(self.widget_20)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.RadioButton_2.setFont(font)
        self.RadioButton_2.setStyleSheet("color: rgb(1, 182, 215);")
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.horizontalLayout_19.addWidget(self.RadioButton_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.widget_25 = QtWidgets.QWidget(self.widget_20)
        self.widget_25.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_9.addWidget(self.widget_25)
        self.label_17 = QtWidgets.QLabel(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_9.addWidget(self.label_17)
        self.SearchLineEdit_2 = SearchLineEdit(self.widget_20)
        self.SearchLineEdit_2.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.SearchLineEdit_2.setFont(font)
        self.SearchLineEdit_2.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.SearchLineEdit_2.setObjectName("SearchLineEdit_2")
        self.verticalLayout_9.addWidget(self.SearchLineEdit_2)
        self.widget_26 = QtWidgets.QWidget(self.widget_20)
        self.widget_26.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_9.addWidget(self.widget_26)
        self.label_37 = QtWidgets.QLabel(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_9.addWidget(self.label_37, 0, QtCore.Qt.AlignBottom)
        self.ZhDatePicker = ZhDatePicker(self.widget_20)
        self.ZhDatePicker.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.ZhDatePicker.setFont(font)
        self.ZhDatePicker.setStyleSheet("border:1px solid rgb(1, 182, 215);\n"
"color: rgb(0, 246, 255);\n"
"border-radius:3px;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ZhDatePicker.setText("")
        self.ZhDatePicker.setObjectName("ZhDatePicker")
        self.verticalLayout_9.addWidget(self.ZhDatePicker)
        self.widget_27 = QtWidgets.QWidget(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_27.sizePolicy().hasHeightForWidth())
        self.widget_27.setSizePolicy(sizePolicy)
        self.widget_27.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_27.setObjectName("widget_27")
        self.verticalLayout_9.addWidget(self.widget_27)
        self.PushButton_7 = QtWidgets.QPushButton(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton_7.sizePolicy().hasHeightForWidth())
        self.PushButton_7.setSizePolicy(sizePolicy)
        self.PushButton_7.setMinimumSize(QtCore.QSize(112, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.PushButton_7.setFont(font)
        self.PushButton_7.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.PushButton_7.setObjectName("PushButton_7")
        self.verticalLayout_9.addWidget(self.PushButton_7)
        self.horizontalLayout_23.addWidget(self.widget_20)
        self.horizontalLayout_23.setStretch(0, 30)
        self.horizontalLayout_23.setStretch(1, 10)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("QWidget#page_5{\n"
"border-image: url(:/img/bj4.png);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"")
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.web = QtWebEngineWidgets.QWebEngineView(self.page_5)
        self.web.page().setBackgroundColor(Qt.transparent)
        self.web.setObjectName("web")
        self.horizontalLayout_24.addWidget(self.web)
        self.widget_22 = QtWidgets.QWidget(self.page_5)
        self.widget_22.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shijian_fenbu_2 = QtWidgets.QPushButton(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shijian_fenbu_2.sizePolicy().hasHeightForWidth())
        self.shijian_fenbu_2.setSizePolicy(sizePolicy)
        self.shijian_fenbu_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.shijian_fenbu_2.setFont(font)
        self.shijian_fenbu_2.setObjectName("shijian_fenbu_2")
        self.verticalLayout_2.addWidget(self.shijian_fenbu_2)
        self.zhoufanmang_2 = QtWidgets.QPushButton(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zhoufanmang_2.sizePolicy().hasHeightForWidth())
        self.zhoufanmang_2.setSizePolicy(sizePolicy)
        self.zhoufanmang_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.zhoufanmang_2.setFont(font)
        self.zhoufanmang_2.setObjectName("zhoufanmang_2")
        self.verticalLayout_2.addWidget(self.zhoufanmang_2)
        self.fee_2 = QtWidgets.QPushButton(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fee_2.sizePolicy().hasHeightForWidth())
        self.fee_2.setSizePolicy(sizePolicy)
        self.fee_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.fee_2.setFont(font)
        self.fee_2.setObjectName("fee_2")
        self.verticalLayout_2.addWidget(self.fee_2)
        self.gaofeng_2 = QtWidgets.QPushButton(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaofeng_2.sizePolicy().hasHeightForWidth())
        self.gaofeng_2.setSizePolicy(sizePolicy)
        self.gaofeng_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.gaofeng_2.setFont(font)
        self.gaofeng_2.setObjectName("gaofeng_2")
        self.verticalLayout_2.addWidget(self.gaofeng_2)
        self.jiedai = QtWidgets.QPushButton(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jiedai.sizePolicy().hasHeightForWidth())
        self.jiedai.setSizePolicy(sizePolicy)
        self.jiedai.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.jiedai.setFont(font)
        self.jiedai.setObjectName("jiedai")
        self.verticalLayout_2.addWidget(self.jiedai)
        self.ciyun = QtWidgets.QPushButton(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ciyun.sizePolicy().hasHeightForWidth())
        self.ciyun.setSizePolicy(sizePolicy)
        self.ciyun.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.ciyun.setFont(font)
        self.ciyun.setObjectName("ciyun")
        self.verticalLayout_2.addWidget(self.ciyun)
        self.shiduan = QtWidgets.QPushButton(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shiduan.sizePolicy().hasHeightForWidth())
        self.shiduan.setSizePolicy(sizePolicy)
        self.shiduan.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.shiduan.setFont(font)
        self.shiduan.setObjectName("shiduan")
        self.verticalLayout_2.addWidget(self.shiduan)
        self.zonghe_2 = QtWidgets.QPushButton(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonghe_2.sizePolicy().hasHeightForWidth())
        self.zonghe_2.setSizePolicy(sizePolicy)
        self.zonghe_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.zonghe_2.setFont(font)
        self.zonghe_2.setObjectName("zonghe_2")
        self.verticalLayout_2.addWidget(self.zonghe_2)
        self.zonghe_3 = QtWidgets.QPushButton(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonghe_3.sizePolicy().hasHeightForWidth())
        self.zonghe_3.setSizePolicy(sizePolicy)
        self.zonghe_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.zonghe_3.setFont(font)
        self.zonghe_3.setObjectName("zonghe_3")
        self.verticalLayout_2.addWidget(self.zonghe_3)
        self.horizontalLayout_24.addWidget(self.widget_22)
        self.horizontalLayout_24.setStretch(0, 40)
        self.horizontalLayout_24.setStretch(1, 10)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setStyleSheet("QWidget#page_6{\n"
"border-image: url(:/img/bj4.png);\n"
"}\n"
"")
        self.page_6.setObjectName("page_6")
        self.PushButton1 = QtWidgets.QPushButton(self.page_6)
        self.PushButton1.setGeometry(QtCore.QRect(290, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.PushButton1.setFont(font)
        self.PushButton1.setStyleSheet("QPushButton\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 127, 200);\n"
"    /*字体颜色为白色*/    \n"
"    color:rgb(255, 255, 255);\n"
"    /*设置按键四角为圆角*/\n"
"    border-radius :5px;\n"
"      \n"
"}    \n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        self.PushButton1.setObjectName("PushButton1")
        self.stackedWidget.addWidget(self.page_6)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget_backgroung)
        wuqixinxi.setCentralWidget(self.centralwidget)

        self.retranslateUi(wuqixinxi)
        self.stackedWidget.setCurrentIndex(4)
        self.PushButton_8.clicked.connect(wuqixinxi.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wuqixinxi)

    def retranslateUi(self, wuqixinxi):
        _translate = QtCore.QCoreApplication.translate
        wuqixinxi.setWindowTitle(_translate("wuqixinxi", "智能停车场数据管理系统"))
        self.zhgl.setText(_translate("wuqixinxi", "账户管理"))
        self.wqtj.setText(_translate("wuqixinxi", "车位统计"))
        self.crkgl.setText(_translate("wuqixinxi", "人工出入管理"))
        self.qzxx.setText(_translate("wuqixinxi", "数据预览"))
        self.whby.setText(_translate("wuqixinxi", "车场现状"))
        self.qywqxx.setText(_translate("wuqixinxi", "数据分析"))
        self.afgl.setText(_translate("wuqixinxi", "待定"))
        self.PushButton_8.setText(_translate("wuqixinxi", "退出"))
        self.label_3.setText(_translate("wuqixinxi", "原用户名:"))
        self.label_26.setText(_translate("wuqixinxi", "原密码:"))
        self.label_33.setText(_translate("wuqixinxi", "新用户名"))
        self.label_34.setText(_translate("wuqixinxi", "新密码:"))
        self.label_35.setText(_translate("wuqixinxi", "确认密码"))
        self.genggai.setText(_translate("wuqixinxi", "更改账户"))
        self.zhuce.setText(_translate("wuqixinxi", "注    册"))
        self.TitleLabel.setText(_translate("wuqixinxi", "车位概览"))
        self.SubtitleLabel.setText(_translate("wuqixinxi", "总车位："))
        self.SubtitleLabel_4.setText(_translate("wuqixinxi", "占用车位："))
        self.bq.setText(_translate("wuqixinxi", "剩余车位："))
        self.label_11.setText(_translate("wuqixinxi", "停车\n"
"历史\n"
"信息\n"
"录入"))
        self.label_19.setText(_translate("wuqixinxi", "编号："))
        self.label_23.setText(_translate("wuqixinxi", "驶出日期"))
        self.label_22.setText(_translate("wuqixinxi", "驶出时间"))
        self.label_21.setText(_translate("wuqixinxi", "进入时间"))
        self.label_12.setText(_translate("wuqixinxi", "星期"))
        self.label_20.setText(_translate("wuqixinxi", "进入日期"))
        self.luru.setText(_translate("wuqixinxi", "录    入"))
        self.luru_2.setText(_translate("wuqixinxi", "获取当前时间"))
        self.label_31.setText(_translate("wuqixinxi", "车辆\n"
"驶入\n"
"登记"))
        self.label_29.setText(_translate("wuqixinxi", "编号："))
        self.label_30.setText(_translate("wuqixinxi", "驶入时间"))
        self.in_time.setText(_translate("wuqixinxi", "右侧获取时间"))
        self.dengji.setText(_translate("wuqixinxi", "登      记"))
        self.get_time.setText(_translate("wuqixinxi", "获取"))
        self.label_32.setText(_translate("wuqixinxi", "车辆\n"
"驶出\n"
"登记"))
        self.label_27.setText(_translate("wuqixinxi", "编号："))
        self.label_28.setText(_translate("wuqixinxi", "驶入时间"))
        self.label_25.setText(_translate("wuqixinxi", "驶出时间"))
        self.out_time_1.setText(_translate("wuqixinxi", "右侧获取时间"))
        self.get_time_1.setText(_translate("wuqixinxi", "获取"))
        self.sel_car.setText(_translate("wuqixinxi", "搜索"))
        self.dengji_1.setText(_translate("wuqixinxi", "登      记"))
        self.label_14.setText(_translate("wuqixinxi", "星期"))
        self.label_16.setText(_translate("wuqixinxi", "时段"))
        self.btnQuery.setText(_translate("wuqixinxi", "刷新"))
        self.btnEdit.setText(_translate("wuqixinxi", "修改"))
        self.label_6.setText(_translate("wuqixinxi", "车辆\n"
"信息"))
        self.label_7.setText(_translate("wuqixinxi", "车牌号："))
        self.label_13.setText(_translate("wuqixinxi", "驶入时间"))
        self.label_15.setText(_translate("wuqixinxi", "星期"))
        self.label_8.setText(_translate("wuqixinxi", "停留时间"))
        self.label_10.setText(_translate("wuqixinxi", "驶出时间"))
        self.label_9.setText(_translate("wuqixinxi", "时段"))
        self.PushButton_4.setText(_translate("wuqixinxi", "编号"))
        self.search_1.setText(_translate("wuqixinxi", "查询"))
        self.PushButton.setText(_translate("wuqixinxi", "搜索"))
        self.label_38.setText(_translate("wuqixinxi", "维护保养登记"))
        self.RadioButton.setText(_translate("wuqixinxi", "单个"))
        self.RadioButton_2.setText(_translate("wuqixinxi", "批量"))
        self.label_17.setText(_translate("wuqixinxi", "编号/柜号"))
        self.label_37.setText(_translate("wuqixinxi", "日期"))
        self.PushButton_7.setText(_translate("wuqixinxi", "录入"))
        self.shijian_fenbu_2.setText(_translate("wuqixinxi", "停车时间分布"))
        self.zhoufanmang_2.setText(_translate("wuqixinxi", "周繁忙统计"))
        self.fee_2.setText(_translate("wuqixinxi", "收入分析"))
        self.gaofeng_2.setText(_translate("wuqixinxi", "停车时段统计"))
        self.jiedai.setText(_translate("wuqixinxi", "接待车辆统计_web"))
        self.ciyun.setText(_translate("wuqixinxi", "词云-web"))
        self.shiduan.setText(_translate("wuqixinxi", "时段-web"))
        self.zonghe_2.setText(_translate("wuqixinxi", "收入分析-web"))
        self.zonghe_3.setText(_translate("wuqixinxi", "停车时间分析-web"))
        self.PushButton1.setText(_translate("wuqixinxi", "Pill push button"))
from PyQt5 import QtWebEngineWidgets
from qfluentwidgets import ComboBox, LineEdit, PasswordLineEdit, SearchLineEdit, SubtitleLabel, TableWidget, TimePicker, TitleLabel, ZhDatePicker
